---
title: "Tips Exploration"
author: "Ben Wagner"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(readxl)
library(dplyr)
library(stringdist)
library(topicmodels)
library(tm)
library(SnowballC)
library(stopwords)
library(ggplot2)
```

## Load Data 
```{r}
tips2022<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2022", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2021<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2021", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2020<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip=1, sheet = "2020", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2019<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2019", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2018<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2018", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2017<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2017", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))

tips2016<-read_excel("C:\\Users\\littl\\OneDrive\\Desktop\\IAA_TIPS\\Copy of MSA 2023 STUDENT TIPS spreadsheet.xlsx", skip = 1, sheet = "2016", col_names = c('tip_1', 'tip_2', 'tip_3', 'anything_else'))
```

<!-- ## Counting the frequency of words -->
<!-- ```{r, eval=FALSE} -->
<!-- stopwords_regex = paste(stopwords('en'), collapse = '\\b|\\b') -->
<!-- stopwords_regex = paste0('\\b', stopwords_regex, '\\b') -->
<!-- stringr::str_replace_all(tips2021, stopwords_regex, '') -->
<!-- frequency <- data.frame(t(stringdist::qgrams(freq = tips2021, q=25))) -->

<!-- frequency<-frequency %>%  -->
<!--   arrange(desc(freq)) -->
<!-- ``` -->

## Term Frequency
#all tips in one column
```{r, one column}
unlisted_tips2022 <- data.frame(unlist(tips2022))
colnames(unlisted_tips2022) <- ("x")
unlisted_tips2021 <- data.frame(unlist(tips2021))
colnames(unlisted_tips2021) <- ("x")
unlisted_tips2020 <- data.frame(unlist(tips2020))
colnames(unlisted_tips2020) <- ("x")
unlisted_tips2019 <- data.frame(unlist(tips2019))
colnames(unlisted_tips2019) <- ("x")
unlisted_tips2018 <- data.frame(unlist(tips2018))
colnames(unlisted_tips2018) <- ("x")
unlisted_tips2017 <- data.frame(unlist(tips2017))
colnames(unlisted_tips2017) <- ("x")
unlisted_tips2016 <- data.frame(unlist(tips2016))
colnames(unlisted_tips2016) <- ("x")
unlisted_tipsALL <- do.call("rbind", list(unlisted_tips2022, unlisted_tips2021, unlisted_tips2020, unlisted_tips2019, unlisted_tips2018, unlisted_tips2017, unlisted_tips2016))
```

#Function to create corpus
```{r, warning=FALSE}
corpus_tm <- function(x){
library(tm)
corpus_tm <- Corpus(VectorSource(x))
}
```

#Function to clean data 
```{r}
clean_corpus <- function(corpus_to_use){
library(magrittr)
library(tm)
corpus_to_use %>%
tm_map(removePunctuation) %>%
tm_map(stripWhitespace) %>%
tm_map(content_transformer(function(x) iconv(x, to='UTF-8', sub='byte'))) %>%
tm_map(removeNumbers) %>%
tm_map(removeWords, stopwords("en")) %>%
tm_map(content_transformer(tolower)) %>%
tm_map(removeWords, c("etc","ie", "eg", stopwords("english")))
}
```


#Function to find frequency
```{r}
find_freq_terms_fun <- function(corpus_in){
doc_term_mat <- TermDocumentMatrix(corpus_in)
freq_terms <- findFreqTerms(doc_term_mat)[1:max(doc_term_mat$nrow)]
terms_grouped <-
doc_term_mat[freq_terms,] %>%
as.matrix() %>%
rowSums() %>%
data.frame(Term=freq_terms, Frequency = .) %>%
arrange(desc(Frequency)) %>%
mutate(prop_term_to_total_terms=Frequency/nrow(.))
return(data.frame(terms_grouped))
}
```

#Tips 2022 Frequency call
```{r, warning=FALSE}
unlisted_tips2022 <- corpus_tm(unlisted_tips2022)
unlisted_tips2022 <- clean_corpus(unlisted_tips2022)
freq_terms2022 <- data.frame(find_freq_terms_fun(unlisted_tips2022))

freq_terms2022 <-freq_terms2022 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2022$year <-2022
```

#Tips 2021 Frequency call
```{r, warning=FALSE}
unlisted_tips2021 <- corpus_tm(unlisted_tips2021)
unlisted_tips2021 <- clean_corpus(unlisted_tips2021)
freq_terms2021 <- data.frame(find_freq_terms_fun(unlisted_tips2021))

freq_terms2021 <-freq_terms2021 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2021$year <-2021
```

#Tips 2020 Frequency call
```{r, warning=FALSE}
unlisted_tips2020 <- corpus_tm(unlisted_tips2020)
unlisted_tips2020 <- clean_corpus(unlisted_tips2020)
freq_terms2020 <- data.frame(find_freq_terms_fun(unlisted_tips2020))

freq_terms2020 <-freq_terms2020 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2020$year <-2020
```

#Tips 2019 Frequency call
```{r, warning=FALSE}
unlisted_tips2019 <- corpus_tm(unlisted_tips2019)
unlisted_tips2019 <- clean_corpus(unlisted_tips2019)
freq_terms2019 <- data.frame(find_freq_terms_fun(unlisted_tips2019))

freq_terms2019 <-freq_terms2019 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2019$year <-2019
```

#Tips 2018 Frequency call
```{r, warning=FALSE}
unlisted_tips2018 <- corpus_tm(unlisted_tips2018)
unlisted_tips2018 <- clean_corpus(unlisted_tips2018)
freq_terms2018 <- data.frame(find_freq_terms_fun(unlisted_tips2018))

freq_terms2018 <-freq_terms2018 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2018$year <-2018
```

#Tips 2017 Frequency call
```{r, warning=FALSE}
unlisted_tips2017 <- corpus_tm(unlisted_tips2017)
unlisted_tips2017 <- clean_corpus(unlisted_tips2017)
freq_terms2017 <- data.frame(find_freq_terms_fun(unlisted_tips2017))

freq_terms2017 <-freq_terms2017 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2017$year <-2017
```

#Tips 2016 Frequency call
```{r, warning=FALSE}
unlisted_tips2016 <- corpus_tm(unlisted_tips2016)
unlisted_tips2016 <- clean_corpus(unlisted_tips2016)
freq_terms2016 <- data.frame(find_freq_terms_fun(unlisted_tips2016))

freq_terms2016 <-freq_terms2016 %>% 
  filter(Term %in% c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help"))
freq_terms2016$year <-2016
```

#Tips All and visual Frequency call
```{r, warning=FALSE}
unlisted_tipsALL <- corpus_tm(unlisted_tipsALL)
unlisted_tipsALL <- clean_corpus(unlisted_tipsALL)
freq_termsALL <- data.frame(find_freq_terms_fun(unlisted_tipsALL))

freq_terms_visual<- freq_terms2022 %>% 
  full_join(freq_terms2021, by=c("Term", "year", "Frequency", "prop_term_to_total_terms")) %>%
  full_join(freq_terms2020, by=c("Term", "year", "Frequency", "prop_term_to_total_terms")) %>% 
  full_join(freq_terms2019, by=c("Term", "year", "Frequency", "prop_term_to_total_terms")) %>%
  full_join(freq_terms2018, by=c("Term", "year", "Frequency", "prop_term_to_total_terms")) %>%
  full_join(freq_terms2017, by=c("Term", "year", "Frequency", "prop_term_to_total_terms")) %>%
  full_join(freq_terms2016, by=c("Term", "year", "Frequency", "prop_term_to_total_terms"))
```


#Slide Visuals
```{r}
level_order<- c("learn", "python", "notes", "time", "program", "classmates", "friends", "trust", "faculty", "help")

ggplot(data = freq_terms_visual, aes(x=year, y=factor(Term, levels = level_order), fill=prop_term_to_total_terms)) + 
  geom_tile()+
  theme_bw()+
  scale_x_continuous()+
  labs(title="Term Frequency", y="Term")+
  scale_x_continuous(breaks = c(2016, 2017, 2018, 2019, 2020, 2021, 2022))+
  guides(fill=guide_legend(title="Percent of Total Terms"))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_gradient(low="#9e7e3e", high = "#000136")
```

